engines:
  duplication:
    enabled: true
    config:
      languages:
        - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    rulesets: "cleancode,codesize,design,naming,unusedcode"
ratings:
  paths:
    - "**.php"
exclude_paths:
  - test/
